NOT TESTED Fix for gazebo

diff --git a/setup_ros2 b/setup_ros2
--- a/setup_ros2
+++ b/setup_ros2
@@ -2,13 +2,13 @@
 
 # Recommended 12GB of memory (tested on 8GB RAM and 8GB Swap)
 
-# set -e
+set -e
 
 # Setup checkpoint
 STEP_FILE="/tmp/setup_ros_step.txt"
 PROGRESS_STEP=0
 STEP=0
-
+SOURCE_NEEDED=0
 
 # Select ROS 2 devel
 DEVEL="humble"
@@ -132,6 +132,7 @@ PROGRESS_STEP=$((PROGRESS_STEP + 1))
 if [ $(checkstep) ] ; then
     STEP=$((STEP + 1))
     sudo apt install ros-${DEVEL}-desktop-full -y
+    SOURCE_NEEDED=1
 fi
 PROGRESS_STEP=$((PROGRESS_STEP + 1))
 
@@ -174,27 +175,16 @@ if [ $(checkstep) ] ; then
     if [ -e ~/rove ] ; then
         echo Skipping mkdir
     else
-        mkdir -p ~/rove
+        mkdir -p ~/rove_ws
     fi
 fi
 PROGRESS_STEP=$((PROGRESS_STEP + 1))
 
 # Leave this outside of checkpoints
 # This is required to prevent skipping a cd
-cd ~/rove
+cd ~/rove_ws
 
-# # 10 Clone Gazebo repo
-# if [ $(checkstep) ] ; then
-#     STEP=$((STEP + 1))
-#     if [ -e ./ros_gz ] ; then
-#         echo Skipping cloning gazebo
-#     else
-#         git clone https://github.com/gazebosim/ros_gz.git -b $DEVEL
-#     fi
-# fi
-# PROGRESS_STEP=$((PROGRESS_STEP + 1))
-
-# 11 Clone Rove repo or skip
+# 10 Clone Rove repo or skip
 if [ $(checkstep) ] ; then
     STEP=$((STEP + 1))
     if [ -e ./rove ] ; then
@@ -205,10 +195,10 @@ if [ $(checkstep) ] ; then
 fi
 PROGRESS_STEP=$((PROGRESS_STEP + 1))
 
-# 12 Install Gazebo
+# 11 Install Gazebo
 if [ $(checkstep) ] ; then
     STEP=$((STEP + 1))
-    sudo apt-get install -y gz-harmonic
+    sudo apt-get install -y gz-harmonic ros-humble-ros-gz-sim ros-humble-ros-gzharmonic-bridge ros-humble-ros-gzharmonic-sim ros-humble-ros-gzharmonic-interfaces
 fi
 PROGRESS_STEP=$((PROGRESS_STEP + 1))
 
@@ -220,7 +210,7 @@ if [ $(printenv | grep -i ROS_DISTRO) = '' ] ; then
     exit 0
 fi
 
-# 13 Init and update rosdep
+# 12 Init and update rosdep
 if [ $(checkstep) ] ; then
     STEP=$((STEP + 1))
     sudo rosdep init
@@ -228,7 +218,7 @@ if [ $(checkstep) ] ; then
 fi
 PROGRESS_STEP=$((PROGRESS_STEP + 1))
 
-# 14 Init and update rosdep
+# 13 Init and update rosdep
 if [ $(checkstep) ] ; then
     STEP=$((STEP + 1))
     sudo apt-get install -y \
@@ -238,6 +228,16 @@ if [ $(checkstep) ] ; then
 fi
 PROGRESS_STEP=$((PROGRESS_STEP + 1))
 
+cd ~/rove_ws/rove
+
+# 14 Import repos
+if [ $(checkstep) ] ; then
+    STEP=$((STEP + 1))
+    vcs import src < rove.repos
+fi
+PROGRESS_STEP=$((PROGRESS_STEP + 1))
+
+
 # 15 Install rosdep packages
 if [ $(checkstep) ] ; then
     STEP=$((STEP + 1))
@@ -245,16 +245,7 @@ if [ $(checkstep) ] ; then
 fi
 PROGRESS_STEP=$((PROGRESS_STEP + 1))
 
-cd ~/rove/rove
-
-# 16 Import repos
-if [ $(checkstep) ] ; then
-    STEP=$((STEP + 1))
-    vcs import src < rove.repos
-fi
-PROGRESS_STEP=$((PROGRESS_STEP + 1))
-
-# 17 Build workspace
+# 16 Build workspace
 if [ $(checkstep) ] ; then
     STEP=$((STEP + 1))
     # ROS2 python disable warning
@@ -265,21 +256,17 @@ if [ $(checkstep) ] ; then
 fi
 PROGRESS_STEP=$((PROGRESS_STEP + 1))
 
-cd ~/rove/ros_gz
-
-
-
-# 19 Add source instructions to bashrc
+# 17 Add source instructions to bashrc
 if [ $(checkstep) ] ; then
     STEP=$((STEP + 1))
     exit
     echo "source /opt/ros/${ROS_DISTRO}/setup${SHELL_EXT}" >> ~/${SHELL_EXT}rc
-    echo "source ~/rove/rove/install/setup${SHELL_EXT}" >> ~/${SHELL_EXT}rc
+    echo "source ~/rove/rove_ws/install/setup${SHELL_EXT}" >> ~/${SHELL_EXT}rc
     echo Make sure to restart your terminal!!!
 fi
 PROGRESS_STEP=$((PROGRESS_STEP + 1))
 
-# 20 Cleanup
+# 18 Cleanup
 if [ $(checkstep) ] ; then
     STEP=$((STEP + 1))
     echo Install successful!
